[workspace]
resolver = "3"
members = [
    "isx",
    "isx-macros",
]

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT"
rust-version = "1.85.0"

[workspace.metadata.release]
tag = false
tag-name = "v{{version}}"
